#pragma once

#include "GLEW/glew.h"

enum ShaderType {
	VERTEX = GL_VERTEX_SHADER,
	FRAGMENT = GL_FRAGMENT_SHADER,
	//GEOMETRY = GL_GEOMETRY_SHADER,
	//TESS_CONTROL = GL_TESS_CONTROL_SHADER,
	//TESS_EVALUATION = GL_TESS_EVALUATION_SHADER,
	//COMPUTE = GL_COMPUTE_SHADER
};
